### ISSUE TITLE
Who should have access for this repository?

### ISSUE THREAD

**Issue by joyeecheung** [nodejs/bluesky#2]
Currently as usual, any new repository created in the organization is under the jurisdiction of @nodejs/tsc and @nodejs/moderation have write access. I can foresee that we'll develop some automation here and will need people to push the merge button - which is separate from actual admin access to the Bluesky account(s).

I propose to create an empty @nodejs/bluesky team for now, while delegating the write access to @nodejs/tsc and @nodejs/moderation first. One doesn't need to be a member of any team to open issues or send a PR here to get the automation going and can just do it, we can figure out a team after we actually got something going on in this repo, to prevent creating another zombie team with no one actually doing anything after the initial signup phase.

**Comment by joyeecheung** [comment]
There is also @nodejs/social which I think can also have write access, though may not be very suitable for/interested in e.g. reviewing code in the GitHub actions.

**Comment by RafaelGSS** [comment]
I'd include @nodejs/releasers too as we'll share the releases on that platform as well.

**Comment by joyeecheung** [comment]
I created @nodejs/bluesky (looks like I cannot make it empty, so the creator - me - is automatically the only member), and added these access:

<img width="846" alt="Screenshot 2024-11-20 at 21 52 40" src="https://github.com/user-attachments/assets/dac1bb90-e47b-4fdc-96ce-46480ba38dc5">

If any existing member of @nodejs/releasers @nodejs/tsc @nodejs/social @nodejs/moderation want to join @nodejs/bluesky feel free to contact me. I will work out a PR about governance in the meanwhile and we can discuss there.
